Release 2.0.0
theforeman/puppet-pulpcore pull request #139
Opened 2020-10-27 20:54 UTC by wbclark

2020-10-27 21:03 UTC, ekohl requested changes
https://github.com/theforeman/puppet-pulpcore/pull/138 should go in first.

2020-10-30 01:00 UTC, wbclark commented
#141 should satisfy that but is blocked on #140 which should have its first commit applied directly to master first in order for tests to run

2020-10-30 02:53 UTC, wbclark commented
Rebased

2020-10-30 12:42 UTC, ehelms approved these changes

2020-10-30 12:45 UTC, merged