Fixes #32112 - Configure api service gunicorn worker timeout
theforeman/puppet-pulpcore pull request #178
Opened 2021-03-17 05:49 UTC by wbclark

2021-03-17 05:50 UTC, wbclark commented
If there is a need to do so, we can configure the timeout for the content service gunicorn workers as well. However the specific issue I faced when syncing multiple large RPM repositories required the gunicorn worker timeout for the api service to be increased from the default 30 seconds.

2021-03-17 09:10 UTC, ekohl requested changes

2021-03-17 09:10 UTC, ekohl commented on manifests/init.pp
> +  Integer[1] $api_service_worker_timeout = 60,
https://docs.gunicorn.org/en/stable/settings.html#timeout states:
> Value is a positive number or 0. Setting it to 0 has the effect of infinite timeouts by disabling timeouts for all workers entirely.
```suggestion
  Integer[0] $api_service_worker_timeout = 60,
```

2021-03-17 15:11 UTC, wbclark commented
@ekohl updated, thanks.

2021-03-17 18:50 UTC, ehelms approved these changes

2021-03-18 10:43 UTC, ekohl approved these changes

2021-03-19 14:10 UTC, merged