Add param for unsave advisory conflict resolution
theforeman/puppet-pulpcore pull request #274
Opened 2023-01-31 15:25 UTC by m-bucher

https://community.theforeman.org/t/katello-incoming-and-existing-advisories-have-the-same-id-but-different-timestamps/23954/8

2023-01-31 16:31 UTC, ekohl requested changes

2023-01-31 16:31 UTC, ekohl commented on templates/settings.py.erb
> +ALLOW_AUTOMATIC_UNSAFE_ADVISORY_CONFLICT_RESOLUTION = <%= scope['pulpcore::allow_automatic_unsafe_advisory_conflict_resolution'] %>
You should convert this to Python booleans. See a few lines below for `CACHE_ENABLED`, or use `to_python()`.

2023-01-31 18:20 UTC, ekohl requested changes
I should have checked this earlier, but this comes from `pulp_rpm` so it should also live in [pulpcore::plugin::rpm](https://github.com/theforeman/puppet-pulpcore/blob/master/manifests/plugin/rpm.pp). See 5e2bfd7e335c63998f4abb8d75647cd9837cc2d0 for an example of how a plugin-specific config option was added earlier.

In this case there is already some inline content so it probably makes sense to move it to a template. While most templates are ERB, I'd like to move to EPP. In 2e2d3ecf486ed2b333e405d883b1bb2c59978911 I added an EPP template. Note how it uses `epp()` (with a context) instead of `template()` and a slightly different context.

2023-02-02 16:23 UTC, ekohl approved these changes
From a quick glance this looks ok and the test coverage should be sufficient.

2023-02-02 16:28 UTC, merged

2023-02-03 08:48 UTC, m-bucher commented
Thanks @ekohl for merging this.
I just remembered that I actually intended to set the default to `true`. What do you think?